server:
  port: 9902
spring:
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev
management:
  endpoints:
    web:
      exposure:
        include: '*'
# Dubbo配置
dubbo:
  application:
    name: cms-dubbo-consumer
  protocol:
    name: dubbo
  registry:
    address: zookeeper://127.0.0.1:2181

mybatis-plus:
  typeAliasesPackage: com.cms.consumer.entity
  mapper-locations: classpath*:com/cms/consumer/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

