server:
  port: 8083
spring:
  application:
    name: cms-service-item
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dtmanage?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&nullCatalogMeansCurrent=true
    username: root
    password: Passw0rd!
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
# 分布式事务配置
seata:
  tx-service-group: mall_tx_group
  enable-auto-data-source-proxy: true
  registry:
    type: nacos
    nacos:
      server-addr: localhost:8848
      namespace: seata_namespace_id
      group: SEATA_GROUP
  config:
    type: nacos
    nacos:
      server-addr: localhost:8848
      namespace: seata_namespace_id
      group: SEATA_GROUP
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true  # 开启服务调用失败处理
  httpclient:
    enabled: false # 关闭httpclient
  okhttp:
    enabled: true  # 开启okhttp
mybatis-plus:
  typeAliasesPackage: com.cms.item.entity
  mapper-locations: classpath*:com/cms/item/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# canal配置
canal:
  ip: localhost
  user: canal
  password: canal
  port: 11111
  defaultDatabaseName: test_jdbc
  destination: example
