server:
  port: 9091
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 42.192.121.230:8848
        enabled: true
    sentinel:
      enabled: true # sentinel开关
      eager: true
      transport:
        dashboard: localhost:8080 # Sentinel控制台地址
        client-ip: localhost
      datasource:
        # 网关限流规则，gw-flow为key，随便定义
        gw-flow:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            dataId: ${spring.application.name}-gw-flow-rules # 流控规则配置文件名：youlai-gateway-gw-flow-rules
            groupId: SENTINEL_GROUP
            data-type: json
            rule-type: gw-flow
        # 自定义API分组，gw-api-group为key，随便定义
        gw-api-group:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            dataId: ${spring.application.name}-gw-api-group-rules # 流控规则配置文件名：youlai-gateway-gw-api-group-rules
            groupId: SENTINEL_GROUP
            data-type: json
            rule-type: gw-api-group
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allow-credentials: true
            allowed-origins: "*"
            allowed-headers: "*"
            allowed-methods:
              - POST
              - GET
              - PUT
              - OPTIONS
              - DELETE
              - PATCH
            max-age: 3600
  redis:
    # Redis服务器连接IP
    host: 42.192.121.230
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: Passw0rd!
    # 连接超时时间（毫秒）
    timeout: 5000
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 16
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 16
        # 连接池中的最小空闲连接 默认 0
        min-idle: 16