server:
  port: 8083
spring:
  application:
    name: cms-service-auth
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true  # 开启服务调用失败处理
  httpclient:
    enabled: false # 默认启用的是HttpClient客户端连接，性能不好
  okhttp:
    enabled: true # 使用okhttp客户端
logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.api.manage.feign.ManageFeignService: debug
