server:
  port: 8083
spring:
  application:
    name: cms-service-auth
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
# 对Feign的支持
feign:
  sentinel:
    enabled: true
logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.api.manage.feign.OauthFeignClientService: debug
mybatis-plus:
  mapper-locations: classpath*:com/cms/auth/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
secure:
  ignored:
    urls: # 安全路径白名单
      - /doc.html
      - /swagger-resources/**
      - /webjars/**
      - /*/api-docs
      - /css/**
      - /js/**
      - /img/**
      - /fonts/**
      - /index.html
      - /actuator/**
      - /druid/**
      - /oauth/**
      - /login/**
      - /logout/**
      - /rsa/publicKey
      - /hello
      - /valid_code
