server:
  port: 8083
spring:
  application:
    name: cms-service-auth
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dtmanage?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&nullCatalogMeansCurrent=true
    username: root
    password: Passw0rd!
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alibaba:   # 配置seata分布式事务解决方案
      seata:
        tx-service-group: fsp_tx_group # 自定义事务组名称需要与seata-server中的对应
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true  # 开启服务调用失败处理
  httpclient:
    enabled: false # 默认启用的是HttpClient客户端连接，性能不好
  okhttp:
    enabled: true # 使用okhttp客户端
logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.api.manage.feign.ManageFeignService: debug
mybatis-plus:
  typeAliasesPackage: com.cms.auth.entity
  mapper-locations: classpath*:com/cms/auth/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
