spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dtcms1.0?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&nullCatalogMeansCurrent=true
    username: root
    password: Passw0rd!
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    # Redis服务器连接IP
    host: localhost
    # Redis服务器连接端口
    port: 7000
    # Redis服务器连接密码（默认为空）
    password: Passw0rd!
    # 连接超时时间（毫秒）
    timeout: 5000
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 16
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 16
        # 连接池中的最小空闲连接 默认 0
        min-idle: 16
  # 配置RabbitMQ服务器
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirm-type: correlated
    publisher-returns: true
      #listener:
      #simple:
      #acknowledge-mode: manual # 设置消费端手动 ack
    #retry:
    #enabled: true   # 是否支持重试