server:
  port: 8083
spring:
  application:
    name: cms-service-auth
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
#对Feign的支持
feign:
  sentinel:
    enabled: true
logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.api.manage.feign.OauthFeignClientService: debug
