spring:
  application:
    name: cms-service-gateway
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev
  cloud:
    loadbalancer:
      retry:
        enabled: false
    gateway:
      routes:
        - id: cms-auth
          uri: lb://cms-service-auth
          predicates:
            - Path=/auth/oauth/**,/auth/anonymous/**,/auth/security/**,/auth/hello,/auth/admin
          filters:
            - StripPrefix=1
        - id: cms-manage
          uri: lb://cms-service-manage
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
secure:  #配置白名单路径
  ignore:
    urls:
      - /auth/oauth/**
      - /auth/anonymous/**
      - /auth/hello
      - /api/operator/page
