server:
  port: 9090
spring:
  application:
    name: cms-service-gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: cms-auth
          uri: lb://cms-service-auth
          predicates:
            - Path=/**
security:
  oauth2:
    resourceserver:
      jwt:
        jwk-set-uri: 'http://localhost:8083/rsa/publicKey' #配置RSA的公钥访问地址
secure:
  ignore:
    urls: #配置白名单路径
      - auth = /anonymous/**
      - auth = /oauth/**
