server:
  port: 8080
spring:
  application:
    name: cms-service-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: cms_routh
          uri: lb://cms-service-manage
          predicates:
            - Path=/**

management:
  endpoints:
    web:
      exposure:
        include: '*'