spring:
  application:
    name: cms-service-gateway
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  cloud:
    loadbalancer:
      retry:
        enabled: false
    gateway:
      routes:
        - id: cms-auth
          uri: lb://cms-service-auth
          predicates:
            - Path=/oauth/**,/hello,/admin
secure:  #配置白名单路径
  ignore:
    urls:
      - /oauth/**
      - /hello
