server:
  port: 9090
spring:
  application:
    name: cms-service-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: cms-auth
          uri: lb://cms-service-auth
          predicates:
            - Path=/**

management:
  endpoints:
    web:
      exposure:
        include: '*'