server:
  port: 8080
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true   #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: cms_routh
          uri: lb://cms-service-manage
          predicates:
            - Path=/**

management:
  endpoints:
    web:
      exposure:
        include: '*'