server:
  port: 9090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        enabled: true
    sentinel:
      enabled: true # sentinel开关
      eager: true
      transport:
        dashboard: localhost:8080 # Sentinel控制台地址
        client-ip: localhost
      datasource:
        # 网关限流规则，gw-flow为key，随便定义
        gw-flow:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            dataId: ${spring.application.name}-gw-flow-rules # 流控规则配置文件名：youlai-gateway-gw-flow-rules
            groupId: SENTINEL_GROUP
            data-type: json
            rule-type: gw-flow
        # 自定义API分组，gw-api-group为key，随便定义
        gw-api-group:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            dataId: ${spring.application.name}-gw-api-group-rules # 流控规则配置文件名：youlai-gateway-gw-api-group-rules
            groupId: SENTINEL_GROUP
            data-type: json
            rule-type: gw-api-group
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allow-credentials: true
            allowed-origins: "*"
            allowed-headers: "*"
            allowed-methods:
              - POST
              - GET
              - PUT
              - OPTIONS
              - DELETE
              - PATCH
            max-age: 3600