server:
  port: 9901
spring:
  application:
    name: cms-dubbo-provider
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev
management:
  endpoints:
    web:
      exposure:
        include: '*'
# Dubbo配置

mybatis-plus:
  typeAliasesPackage: com.cms.provider.entity
  mapper-locations: classpath*:com/cms/provider/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

