version: "3"
services:
  dt-xxl-job:
    image: xuxueli/xxl-job-admin:2.3.0
    container_name: dt-xxl-job
    restart: unless-stopped # 指定容器退出后的重启策略为始终重启，但是不考虑在Docker守护进程启动时就已经停止了的容器
    ports:                  # 映射端口
      - "9091:8080"
    environment:            # 设置环境变量,相当于docker run命令中的-e
      TZ: Asia/Shanghai
      PARAMS: "--spring.datasource.username=root --spring.datasource.password=Passw0rd! --spring.datasource.url=jdbc:mysql://42.192.121.230:3306/xxl_job?Unicode=true&characterEncoding=UTF-8"
    volumes:                # 数据卷挂载路径设置,将本机目录映射到容器目录
      - /dt/job/data/applogs:/data/applogs
