version: "3"
services:
  dt-redis:
    image: redis:latest
    container_name: dt-redis
    restart: unless-stopped # 指定容器退出后的重启策略为始终重启，但是不考虑在Docker守护进程启动时就已经停止了的容器
    ports:                  # 映射端口
      - "6379:6379"
    environment:            # 设置环境变量,相当于docker run命令中的-e
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    volumes:                # 数据卷挂载路径设置,将本机目录映射到容器目录
      - /dt/redis/config/redis.conf:/etc/redis/redis.conf
      - /dt/redis/data:/data
    command: redis-server /etc/redis/redis.conf
