server:
  port: 8082
spring:
  application:
    name: cms-service-manage
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true  # 开启服务调用失败处理