server:
  port: 8082
spring:
  application:
    name: cms-service-manage
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 42.192.121.230:8848
        enabled: true
  cache:
    type: EHCACHE
    ehcache:
      config: classpath:ehcache.xml
management:
  endpoints:
    web:
      exposure:
        include: '*'

# OpenFeign配置
feign:
  sentinel:
    enabled: true
  httpclient:
    enabled: false            # 关闭httpclient
  okhttp:
    enabled: true             # 开启okhttp
  client:                     # openfeign远程访问的默认超时时间是1s，可以使用如下配置方式修改，也可以使人ribbon方式配置
    config:
      default:                # OpenFeign默认调用所有服务的默认超时时间,如果针对某个服务配置，可将default换成服务名称即可
        connectTimeout: 5000  # 建立连接所用的时间，适用于网络状况正常的情况下，两端连接所需要的时间
        readTimeout: 5000     # 指建立连接后从服务端读取到可用资源所用的时间,默认为1s
#ribbon:                      #设置feign客户端超时时间(OpenFeign默认支持ribbon)
#  ReadTimeout: 2000
#  ConnectTimeout: 2000

mybatis-plus:
  typeAliasesPackage: com.cms.manage.entity
  mapper-locations: classpath*:com/cms/manage/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  typeEnumsPackage: com.cms.common.tool.enums

