server:
  port: 8082
spring:
  application:
    name: cms-service-manage
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
# 开启服务调用失败处理
feign:
  sentinel:
    enabled: true
mybatis-plus:
  typeAliasesPackage: com.cms.manage.entity
  mapper-locations: classpath*:com/cms/manage/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
