server:
  port: 8085
spring:
  application:
    name: cms-service-document
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
# 开启服务调用失败处理
feign:
  sentinel:
    enabled: true
mybatis-plus:
  typeAliasesPackage: com.cms.document.entity
  mapper-locations: classpath*:com/cms/document/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#Minio文件服务器配置=====================================
minio:
  client:
    url: http://42.192.121.230:9000       # MinIo 上传地址
    accessKey: admin                      # 账号
    secretKey: Passw0rd!                  # 密码
  http:
    url: http://42.192.121.230:9000       # MinIo 公网地址

