server:
  port: 8083
spring:
  application:
    name: cms-service-flow
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:9092
        port: 8719
management:
  endpoints:
    web:
      exposure:
        include: '*'