server:
  port: 8086
spring:
  application:
    name: cms-service-oauth
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 42.192.121.230:8848
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
# 对Feign的支持
feign:
  sentinel:
    enabled: true
  httpclient:
    enabled: false # 关闭httpclient
  okhttp:
    enabled: true  # 开启okhttp
#SpringBoot的日志级别默认为info,大于full,导致feign的日志配置不会输出，所以加以下配置
logging:
  level:
    com.api.manage.feign.OauthFeignClientService: debug
mybatis-plus:
  mapper-locations: classpath*:com/cms/oauth/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
secure:
  ignored:
    urls: # 安全路径白名单
      - /doc.html
      - /swagger-resources/**
      - /webjars/**
      - /*/api-docs
      - /css/**
      - /js/**
      - /img/**
      - /fonts/**
      - /index.html
      - /actuator/**
      - /druid/**
      - /oauth/**
      - /security/logout/**
      - /anonymous/**
      - /rsa/publicKey
      - /hello
      - /login.html
      - /favicon.ico
wechat:  #微信小程序配置
  app:
    appid: wxa68b60e7906e6586
    secret: c828a2844a48405c9edb652fb17c2439

